# Generated by Django 3.0.7 on 2020-08-16 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='upload',
            field=models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
