# Generated by Django 3.0.7 on 2020-08-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='upload',
            field=models.FileField(upload_to=''),
        ),
    ]
