# Generated by Django 3.0.7 on 2020-08-16 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfApp', '0002_auto_20200816_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddata',
            name='upload',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
